### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by sindresorhus** [chalk/chalk#167]
We could use some help with issues in related modules:

- [x] Support fullwidth characters: https://github.com/chalk/slice-ansi/issues/4
- [x] Support for unicode surrogate pairs: https://github.com/chalk/slice-ansi/issues/5
- [x] Adds moot escape codes: https://github.com/chalk/slice-ansi/issues/6
- [x] Use AVA test macros in the tests: https://github.com/chalk/chalk-cli/issues/5

**Comment by Qix-** [comment]
Many thanks to @kevva for the work on this :)

**Comment by kevva** [comment]
I think https://github.com/chalk/slice-ansi/pull/10 needs to land before this is *truly* fixed :).

**Comment by Qix-** [comment]
Oh I just saw 'merged' and figured it was done. I think it's sufficient for this ticket though.
