### ISSUE TITLE
Roadmap ideas

### ISSUE THREAD

**Issue by sindresorhus** [chalk/chalk#300]
Here are the goals for Chalk 3:

- [x] Drop support for Node.js 4
- [ ] Bundle all dependencies at publish-time. I would usually never do this, but Chalk is one of the most popular packages on npm. We could use Browserify or Webpack something to make it a single file.
- [ ] `require('chalk/lite')` which only includes support for 16-bit. For when you need something fast and simple for logging.
- [x] Move to class-based construction: #188 
- [x] Improve speed, both require speed (#180) and execution speed (https://github.com/chalk/chalk/issues/333).
	For execution speed we could add fast-paths for when only using 16 colors, which is the most common use-case.
- [ ] Stop using the `color-convert` module. It's too slow and flexible. We don't really need that many ways of specifying colors. I would prefer to support *just* keywords, HEX, RGB. I'm honestly not sure if this is feasible. Just an idea for improving the package size and performance. Alternatively, make `color-convert` tree-shakable, so we only get the parts we actually need.
- [ ] Browser DevTools support built-in? This has been a common request and as long as it doesn't require too much code (and no new dependencies), I welcome a PR adding it.

**We welcome contributions to help with this effort and ideas for the v3 goals. 🙌**

---

@Qix- Thoughts? Anything else?

**Comment by sindresorhus** [comment]
Sure, Rollup would work too.

**Comment by Qix-** [comment]
Sorry @sindresorhus, commented too quickly. Edited my comment with more information.

**Comment by pspeter3** [comment]
Is anyone owning the TypeScript conversion? I would be happy to help with that and bundling during publish

**Comment by Qix-** [comment]
@pspeter3 go for it - pull requests are always welcomed.

**Comment by felixfbecker** [comment]
I dont really understand the benefit of bundling. Why can’t the consumer bundle? If the packages bundle, consumers lose the ability to dedupe, which makes the end bundle larger, not smaller

**Comment by jaylinski** [comment]
Another goal could be to reduce the install size: https://packagephobia.now.sh/result?p=chalk

(Although it's already pretty good.)

**Comment by Qix-** [comment]
@jaylinski 90 kilobytes is not a lot. I'm not worried about that, really.

@styfle good catch, thanks for submitting that PR to them.

I'm also on the fence about bundling. I don't see a lot of practical benefits _right now_ since the bundling tech just isn't there. We'd have to supply both an `import`/`export` version of the modules (for bundlers) **plus** a compiled version that worked in Node, effectively doubling the publish size and complexity.

Otherwise we bundle, which has a number of downsides:

- No vulnerability reports upon install
- No deprecation reports upon install (and no letting npm automatically select versions for you in the event something gets deprecated)
- Guaranteed `n * m` install size were `n` is the number of different versions of Chalk within a large project (could be many, many times) and `m` is the number of dependencies Chalk has - as @felixfbecker mentioned

I'm sure there are other downsides that I'm missing but it all feels like a hack and a move _backwards_.

I'm not convinced either.

**Comment by dylang** [comment]
*If* the string template feature is kept around:

* Support multi-line colors, such as 
```json
chalk`{blue
This is
blue
}`
```
* Don't throw errors when encountering unclosed `{`, such as multiline-JSON strings.
```
chalk`{
  "foo": "Bar"
}`
```

* Exposed the templating feature as a function.

```js
// This hack lets chalk template our strings, like '{blue i am blue}'
const usingChalkTemplates(string) => {
    const array = [string];
    array.raw = [string.replace(/\\/g, '\\\\')];
    try {
        return chalk(array);
    } catch {
        // Chalk throws errors on { in strings containing json.
    }
    return arg;
}

// Would be helpful:
const usingChalkTemplates(string) => chalk.template(string)
```

*If* it is removed for size/maintainability, then I hope it can continue as a separate package. We don't use it much, but when we do it helps large blobs of text with colors, such as `--help` screens, be easier to read and write.

I also have a logger I'm working on that uses it to support color in the logger without having to import `chalk` every time you want a little color in a log message. 

```js
log.info(`Development server {blue.underline ${hostname}:${port}} is ready.`);
```

I don't know if this feature of chalk has caught on, but it's been convenient.

**Comment by DerTieran** [comment]
> @sindresorhus / community - what profiling tools are standard now? I wish there was something that could visualize flame graphs (maybe Addy Osmani knows something about this) - but in my albeit quick and limited research I couldn't find anything.
> 
> Having a really strong handle as to _what_ is slowing us down would be beneficial.

@Qix- I really like [`0x`](https://github.com/davidmarkclements/0x) to profile node scripts.

*FYI: Running the hello world example from the readme it looks like [`color-convert/conversions.js`](https://github.com/Qix-/color-convert/blob/master/conversions.js) is one of the bottlenecks.*

**Comment by Qix-** [comment]
@dylang:

> Support multi-line colors, such as

That should be supported already. If it isn't, let's make sure to get a bug report submitted.

> Don't throw errors when encountering unclosed `{`, such as multiline-JSON strings.

Those need to be escaped (`\{`). Again, if that doesn't work a bug report should be submitted.

---

@DerTieran ayy 🎉 that will work, thanks!

I wonder if it's the BFS that occurs with `color-convert` - I've opened a ticket to perform this BFS at publish time instead of runtime: Qix-/color-convert#56

**Comment by callumlocke** [comment]
> I'm open to someone rewriting Chalk in TypeScript if they also do #188.

Any interest in using Flow? Either way it would be good to provide out-of-the-box type definitions for both TypeScript and Flow.

**Comment by nyteshade** [comment]
Flow type is far better for debugging purposes, can be stripped of types with Babel and other tools easily enough and still offers all the same typing as you’d get with typescript while adhering to ES6 and JavaScript standards.

**Comment by sindresorhus** [comment]
> I would, however, like to see a clear idea of how the new Chalk would work API-wise for both Typescript users as well as ye olde Javascript users:

I haven't really spent any time thinking about that yet. Maybe. The main driver for rewriting in TS is that we'll have a build step anyway with bundling, so might just as well rewrite in TS so we don't have to also maintain the TS definition file separately.

> So how do I publish to npm in a way that we can use it with Rollup?

https://babeljs.io/blog/2018/06/26/on-consuming-and-publishing-es2015+-packages

> I dont really understand the benefit of bundling. Why can’t the consumer bundle? If the packages bundle, consumers lose the ability to dedupe, which makes the end bundle larger, not smaller

The benefit is require speed and less dependencies, so faster installs. Usually, this would not be a problem, but Chalk is just used so much. Chalk is for Node.js. The consumer would never bundle themselves. We don't really loose much on not being able to dedupe as most of our dependencies we have only we use, so they usually won't get deduped anyway.

> After looking through chalk and it's dependencies, it will be quite hard to decrease the install size without removing dependencies like ansi-colors.

Note: It's `ansi-styles`, not `ansi-colors`.

> We'd have to supply both an import/export version of the modules (for bundlers) plus a compiled version that worked in Node, effectively doubling the publish size and complexity.

No, we would only have one compiled version.

**Comment by sindresorhus** [comment]
> Any interest in rewriting it in Flow?

No, I'm used to TypeScript and prefer that.

**Comment by felixfbecker** [comment]
> Chalk is for Node.js. The consumer would never bundle themselves.

Consumers that are actually impacted by require speed already bundle, e.g. Electron apps like VS Code, or CLIs like yarn. I doubt this impacts the average consumer. If it does, having one of its many dependencies be bundled probably won't have a noticeable impact. Would be nice to see some numbers.

> We don't really loose much on not being able to dedupe as most of our dependencies we have only we use, so they usually won't get deduped anyway.

If they are really not used by anyone else, why are they separate packages in the first place?
I would find it concerning if packages start adopting this approach of bundling deps. It's npm's job to resolve dependencies, and only the top-level consumer should bundle. Some other concerns have been mentioned like what if there is a security vulnerability reported, and `npm audit` won't report it, and nobody has the ability to upgrade through a soft range. What if the top-level consumer bundles, and only uses a fraction of chalk API (and transitive dependencies), but tree shaking cannot kick in because chalk and its deps _are already_ bundled (one might argue that this is a hypothetical example, but this is what gives me an uncomfortable feeling about this).

**Comment by wcastand** [comment]
Hello everyone,

i'd like to help, the color-convert seems like something i could work on if no one is already doing it.
Did you choose a solution between the two proposed in the top post (make color-convert tree-shakable or write your own color converting library to handle less case and make it smaller) ?

if you think of something else i could help more, let me know :)

**Comment by sindresorhus** [comment]
@wcastand Probably best to start with trying to make `color-convert` tree-shakable. We can have rewriting as a backup plan.

**Comment by wcastand** [comment]
@sindresorhus ok, i'll look into it on the color-convert repo then, thank for the quick answer :)

**Comment by stevemao** [comment]
I'm also not sure about bundling. If perf is an issue for me I would bundle it myself. It's very easy for consumers to cherry-pick which node modules to bundle (I use serverless-webpack)

**Comment by Berkmann18** [comment]
Regarding the browser dev tools support, unless there's a better way, doing something [like this](https://gist.github.com/davidgilbertson/6eae478d9a197bfa1b4dfbef38f787e5) might be the way to go.

**Comment by felixfbecker** [comment]
CSS styles in browser `console.log()` seems to be widely supported, but I think you can't just embed it in a string, you would need to make chalk return an array to be spread into a `console.log()` call.

I would absolutely love a cross-environment way to color output.

**Comment by sindresorhus** [comment]
@stevemao No, not like the above example at least. That just makes it harder to write and read. Chalk is already composable. Can you provide examples of problems you're having with the existing API? It's better to start with that than a solution.

Tree-shaking is meaningless for Chalk as it's for Node.js and even if you took your Node.js project through Webpack/Rollup, it would only save a few bytes at best, as it will still require everything except for the ansi style definition, [which is tiny](https://github.com/chalk/ansi-styles/blob/fb5b656d9fce745881c36deb8ff800b5080d9f89/index.js#L28).

**Comment by wtgtybhertgeghgtwtg** [comment]
On the contrary, it'd effectively be the same as whichever you have as the default export, but with bloat from the other mixed in.

For the record, I'm opposed to bundling dependencies.  It prevents deduplication and can obscure the use of insecure or restrictively licensed packages.

**Comment by sindresorhus** [comment]
Chalk v3 **beta** is out. Please help us test it: https://github.com/chalk/chalk/releases/tag/v3.0.0-beta.1

**Comment by sugoidesune** [comment]
I would love to be able to ditch the `console.log` and simply write 
`chalk.yellow('Warning!')`
and chalk would internaly do the console.log.

OR

console.log.yellow('Warning')

**Comment by Qix-** [comment]
@sugoidesune That's never going to happen, sorry.

**Comment by dlong500** [comment]
@sugoidesune Nothing would stop you from making your own wrapper that could do exactly what you propose.  I've made plenty of console wrappers to reduce boilerplate and/or add other capabilities.

**Comment by sindresorhus** [comment]
> It's already a feature:

PR welcome to mention browser support in the readme. Should link to a source that describes the Chrome support and if there are any other browsers that support it.

**Comment by sindresorhus** [comment]
> No for IE 11.

We don't support IE (nor should anyone), but this is not the place to discuss that.

**Comment by fregante** [comment]
> * `require('chalk/lite')` which only includes support for 16-bit. For when you need something fast and simple for logging.

Yes please, but do it the other way around: the default entry point should be the lite one because that's what most people will use.

> * I would prefer to support _just_ keywords, HEX, RGB

Yes please! `color-convert` is [46% of this chalk](https://bundlephobia.com/result?p=chalk@4.1.0) and is slow to load. Keywords, hex and RGB only need the `color-name` package. Nobody _really_ needs `hsl` in the console.

**Comment by Qix-** [comment]
> Yes please, but do it the other way around: the default entry point should be the lite one because that's what most people will use.

This literally won't solve anything if color-convert is still a dependency...

> Yes please! color-convert is 46% of chalk and is slow to load.

Color convert is 13.1kB on the wire. If this is a serious concern for you, please explain in detail why that is.

> Nobody _really_ needs hsl in the console.

[citation needed]

**Comment by fregante** [comment]
> This literally won't solve anything if color-convert is still a dependency...

Don’t quote me, quote the original post for the “lite” idea

> Color convert is 13.1kB on the wire. If this is a serious concern for you, please explain in detail why that is.

1. Color convert is slow to load and you’re aware of this: https://github.com/Qix-/color-convert/pull/59. Chalk was even changed to load it lazily for this reason. 
2. I like `npx` so every byte counts since the user feels it almost every time they launch a command.

I used rollup on my npx-able tool and the bundle ended up being 1.2MB. By dropping/replacing unnecessary libraries and got the it to 1/4 the size. Also the original 11s run time is now 1.4s. 

By the look of this post (which, again, isn’t mine) optimizing performance (by also dropping color-convert) is a shared concern.

**Comment by fregante** [comment]
> > Nobody _really_ needs hsl in the console.
> 
> [citation needed]

Ok.

```sh
# Find direct dependents
❯ npx npm-dependants chalk | tee list | wc -l
    7171

# Download their tarballs (stopped after the first 3500 packages)
❯ for dep in (cat list); do wget (npm view $dep dist.tarball) & endfor

# Extract while keeping the folder name
❯ for t in *.tgz ; do
     bn=$(basename "$t" .tgz)
     mkdir -p "$bn"
     tar xfz "$t" -C "$bn"
     mv "$t" "$bn"
  endfor
```

```js
❯ rg chalk.red --count --glob '*.js' | wc -l
    2447

❯ rg chalk.bold --count --glob '*.js' | wc -l
    1117

❯ rg chalk.keyword --count --glob '*.js' | wc -l
      47

❯ rg chalk.rgb --count --glob '*.js' | wc -l
      25

❯ rg chalk.hsl --glob '*.js'
debug-utils-1.0.0-alpha.33/package/index.js
46:  comment: chalk.hsl(30, 20, 50),

done-rainbow-0.1.2/package/index.js
20:                chars.push(chalk.hsl(hue, 100, 50)(c));

lumberjack-1.1.2/package/index.js
323:					message = chalk.hsl(match[1], match[2], match[3])(message)

cli-style-0.1.1/package/dist/index.js
23: * hsl - Example: chalk.hsl(32, 100, 50).bold('Orange!')

debug-utils-5.0.0/package/index.js
72:  comment: chalk.hsl(30, 20, 50),
```

Of these, literally one example _needs_ `hsl` and it's just a "fun" package.

Let me know if you want me to run any other commands on these 3500 dependencies before I delete them.

**Comment by wtgtybhertgeghgtwtg** [comment]
That isn't necessarily the only way people can call it.  For example, `ink` specifically depends on this, but [accesses it a little differently](https://github.com/vadimdemedes/ink/blob/b114bebc5dae4f4bf35392abda4f99e3fcfb840b/src/colorize.ts#L66).

**Comment by fregante** [comment]
Yes, but this is to show that the vast majority does not need it. Every dynamic access like that is done by middleman packages which just relay `color-convert` like ansi-style does, like chalk does through ansi-style, and so on. And then nobody uses them in the end.

**Comment by Qix-** [comment]
Yep, I was thinking specifically about Ink with my previous comment.

It's up to @sindresorhus. He can decide.

**Comment by sindresorhus** [comment]
Alright. Let's do this:

- No `chalk/lite`.
- Remove `hsl`, `hsv`, `hwb`, `ansi`.
- Remove `color-convert` as a dependency. Inline the logic to convert HEX/RGB.

Anyone actually needing more, like Ink, can easily use `color-covert` themselves. We can document this.

Open question: Should we keep `ansi265`?

**Comment by Richienb** [comment]
> Should we keep `ansi265`?

I've never actually had to use `ansi256` directly so in my opinion, there's no need to keep it.

**Comment by Qix-** [comment]
Yes please keep `ansi256`. The rest sounds fine.

**Comment by Qix-** [comment]
Further, we should drop upscaling as brought up by #370. I agree, years later, that this choice was probably not optimal. In my defense, we didn't really know how the 256/16m landscape would look when we added support (truecolor had basically just arrived, all of the linux folks thought it'd die immediately).

We should treat the three models individually except for the case of downscaling to a supported level.

**Comment by vadimdemedes** [comment]
Of course, Ink has a [`colorize` function](https://github.com/vadimdemedes/ink/blob/master/src/colorize.ts) that accepts any color string (e.g. `rgb(255, 255, 255)`), parses and applies the color. I'm pretty sure it can be adapted to any chalk API. I thought about removing `hsl`, `hsv` and `hwb` formats too to simplify things.

**Comment by Richienb** [comment]
@sindresorhus Do we plan to bundle chalk?

If not, we can close this issue since every other point has been completed.

**Comment by fregante** [comment]
There are 2 breaking changes on `main`, but I don't think I see this comment in there: https://github.com/chalk/chalk/issues/300#issuecomment-730972576

**Comment by fregante** [comment]
@Richienb I think only this is missing, which can be moved to a new issue: 

> Browser DevTools support built-in? This has been a common request and as long as it doesn't require too much code (and no new dependencies), I welcome a PR adding it.

**Comment by Richienb** [comment]
> @Richienb I think only this is missing, which can be moved to a new issue:
> 
> > Browser DevTools support built-in? This has been a common request and as long as it doesn't require too much code (and no new dependencies), I welcome a PR adding it.

https://github.com/chalk/chalk/commit/b31d6fb48a570d9be48044abe656c36dcac094e4

**Comment by sindresorhus** [comment]
> Do we plan to bundle chalk?

No, I no longer think it's worth it.

**Comment by CEbbinghaus** [comment]
> > @Richienb I think only this is missing, which can be moved to a new issue:
> > > Browser DevTools support built-in? This has been a common request and as long as it doesn't require too much code (and no new dependencies), I welcome a PR adding it.
> 
> [b31d6fb](https://github.com/chalk/chalk/commit/b31d6fb48a570d9be48044abe656c36dcac094e4)

This doesn't seem to be working for me? is there an option in chrome that needs to be toggled?

**Comment by CEbbinghaus** [comment]
> This doesn't seem to be working for me? is there an option in chrome that needs to be toggled?

After doing some digging I figured out why it wasn't working and submitted Pr #518.
