### ISSUE TITLE
Improve Windows support

### ISSUE THREAD

**Issue by sindresorhus** [chalk/chalk#76]
We've already [done a lot](https://github.com/chalk/chalk/issues?utf8=%E2%9C%93&q=windows) to improve Windows support.

Here are some more things I think could be done:
- [x] `underline` support on Windows. [`libuv` issue](https://github.com/libuv/libuv/issues/438)
- [ ] `hidden` support on Windows. [`libuv` issue](https://github.com/libuv/libuv/issues/439)
- [ ] `dim` support on Windows. [`libuv` issue](https://github.com/libuv/libuv/issues/440)

_(Help us out by commenting or doing a PR on the above issues)._

**Comment by Qix-** [comment]
I'll take care of them. libuv/libuv#440 needs some talk, though.

**Comment by sindresorhus** [comment]
For anyone looking here, give this one 3 votes if you want the Windows story to improve: https://wpdev.uservoice.com/forums/266908-command-prompt/suggestions/6509361-provides-support-for-ansi-colors-like-in-bash

**Comment by Qix-** [comment]
Done and done.

**Comment by Qix-** [comment]
@sindresorhus underline support on windows is simply [not going to happen](https://github.com/libuv/libuv/issues/438#issuecomment-125722902).

**Comment by sindresorhus** [comment]
@Qix- Oh, missed that. That sucks. Appreciate you looking into it though :)

**Comment by vidartf** [comment]
Windows 10 has support for ANSI codes in its terminals (cmd + powershell). However, I cannot seem to get colors with chalk to work there. Is this supported?

**Comment by sindresorhus** [comment]
@vidartf It will be supported whenever https://github.com/libuv/libuv/commit/445e3a1f06b2a049e2b50b7edf2992ce80167014 lands in Node.js

**Comment by Qix-** [comment]
Finally.

**Comment by Qix-** [comment]
Closing in favor of Microsoft/BashOnWindows#2174 and #145. Let me know if this should be re-opened for any reason, @sindresorhus.
